### ISSUE TITLE
Wrap RabbitMQ client methods

### ISSUE THREAD

**Issue by viartemev** [viartemev/the-white-rabbit#150]
Write Kotlin-style wrappers for rabbitmq-client methods

**Comment by viartemev** [comment]
@asm0dey what do you think about it?

**Comment by asm0dey** [comment]
Generally speaking I like this idea. But also I understand that abstractions should not leak. Design of wrappers should be as transparent as possible and all the methods of underlying RabbitMQ libs/classes should be available to end-user (aka developer).

**Comment by asm0dey** [comment]
Also I'm strongly unsure about good-first-issue label: this task needs extensive description, which is absent currently.
