### ISSUE TITLE
Add JMH benchmark for Vertx RabbitMQ client

### ISSUE THREAD

**Issue by viartemev** [viartemev/the-white-rabbit#164]
A link to Vertx RabbitmMQ Kotlin lib: https://github.com/vert-x3/vertx-lang-kotlin/blob/master/vertx-lang-kotlin/src/main/kotlin/io/vertx/kotlin/rabbitmq/RabbitMQClient.kt

**Comment by viartemev** [comment]
Vertx RabbitMQ client doesn't have API for confirming publishing.

**Comment by asm0dey** [comment]
Over time I tend to think worse and worse about vert.x
