### ISSUE TITLE
Invocations of Channel#basicPublish is blocking

### ISSUE THREAD

**Issue by viartemev** [viartemev/the-white-rabbit#179]
Invocations of `Channel#basicPublish` is blocking if a [resource-driven alarm](http://www.rabbitmq.com/alarms.html) is in effect.
We need to add default timeout and ability to set up this timeout in consumer.

**Comment by wrover** [comment]
An ideal solution would be to have a cancellable coroutine, but I am afraid the only way to interrupt this blocking call is to close the channel.

**Comment by viartemev** [comment]
@wrover There is `withTimeout` method, we can use it with default timeout and provide a way to set it up. Another option is [blocking connections notification](https://www.rabbitmq.com/connection-blocked.html)

**Comment by wrover** [comment]
The latter is worthwhile, I'll read it. Regarding `withTimeout` I am still struggling writing a working example. Take a look if you wonder -- https://gist.github.com/wrover/0becefe45bcc1d6110be96e1e6354f26
